name: Pull Request

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target branch (${{ github.base_ref }})
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        fetch-depth: 1
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
        fetch-depth: 1
    - name: Check if the PR adds tabs in source files
      run: .github/scripts/check-no-tabs.sh origin/${{ github.base_ref }} HEAD

  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Install distro packages
      run: |
        DEBIAN_FRONTEND=noninteractive apt-get -y update
        DEBIAN_FRONTEND=noninteractive apt-get -y install libboost-dev zlib1g-dev libgtest-dev libeigen3-dev libzstd-dev ninja-build meson
    - uses: actions/checkout@v2
    - name: meson setup
      run: meson setup builddir
    - name: ninja build
      run: ninja -C builddir
    - name: ninja build unittests
      run: ninja -C builddir unittests
    - name: run unittests
      run: |
        ./builddir/unittests \
          --gtest_filter=-LinuxThermalFixture.CurrentMachine_TestUsingSingletomTemperaturesOnCurrentMachine # this test doesn't execute properly in a github runner

